services:
  api:
    container_name: api
    build: .
    ports:
      - "3333:3333"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    restart: always
    command: ["npx prisma generate && npm run migrate && npm run start"]